import './globals.css'
import { Suspense } from "react";
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { ToastContainer } from '@/utils/toast'
import { StateProvider } from '@/contexts/StateContext'
import ThemeSuspense from '@/components/theme/ThemeSuspense'
import MuiTheme from './theme/MuiTheme';

const robotoFont = Roboto({ weight: '300', subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'ShopTECH 2.0',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoFont.className}>
        <ToastContainer />
        <StateProvider>
          <MuiTheme >
            <Suspense fallback={<ThemeSuspense />}>
              {children}
            </Suspense>
          </MuiTheme>
        </StateProvider>
      </body>
    </html>
  )
}
